"""
Template engine. Takes an AgentSpec and writes a complete agent directory.

Generated structure mirrors reference_agent/:

    <name>/
    ├── README.md
    ├── __init__.py
    ├── agent.yaml
    ├── runner.py
    ├── prompts/
    │   ├── system.j2
    │   ├── classification.j2
    │   ├── <flow>.j2  × N (one per in-scope intent)
    │   └── handoff.j2
    ├── tools/
    │   ├── __init__.py
    │   └── <tool>.py × N
    └── evals/
        ├── __init__.py
        └── routing/
            ├── __init__.py
            └── golden.jsonl

Generated files are runnable: imports resolve, prompts render, runner can be
invoked. To actually triage real data, the user fills in tool `call()` stubs
with their own backend.
"""

import json
import os
from pathlib import Path
from textwrap import dedent

from scaffold_agent.spec import AgentSpec, IntentSpec, ToolSpec, FlowSpec


def generate(spec: AgentSpec, output_dir: Path) -> list[Path]:
    """
    Generate the full directory structure for the spec.

    Returns the list of files written. Idempotent — overwrites existing files.
    """
    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    # Top-level files
    written.append(_write(output_dir / "__init__.py", ""))
    written.append(_write(output_dir / "README.md", _render_readme(spec)))
    written.append(_write(output_dir / "agent.yaml", _render_manifest(spec)))
    written.append(_write(output_dir / "runner.py", _render_runner(spec)))

    # Prompts
    prompts_dir = output_dir / "prompts"
    prompts_dir.mkdir(exist_ok=True)
    written.append(_write(prompts_dir / "system.j2", _render_system_prompt(spec)))
    written.append(_write(prompts_dir / "classification.j2", _render_classification_prompt(spec)))
    written.append(_write(prompts_dir / "handoff.j2", _render_handoff_prompt(spec)))
    for flow in spec.flows:
        written.append(_write(
            prompts_dir / f"{flow.intent}_flow.j2",
            _render_flow_prompt(spec, flow),
        ))

    # Tools
    tools_dir = output_dir / "tools"
    tools_dir.mkdir(exist_ok=True)
    written.append(_write(
        tools_dir / "__init__.py",
        _render_tools_init(spec),
    ))
    for tool in spec.tools:
        written.append(_write(
            tools_dir / f"{tool.name}.py",
            _render_tool(tool),
        ))

    # Evals
    evals_dir = output_dir / "evals"
    evals_dir.mkdir(exist_ok=True)
    written.append(_write(evals_dir / "__init__.py", ""))
    routing_dir = evals_dir / "routing"
    routing_dir.mkdir(exist_ok=True)
    written.append(_write(routing_dir / "__init__.py", ""))
    written.append(_write(
        routing_dir / "golden.jsonl",
        _render_golden_set(spec),
    ))

    return written


def _write(path: Path, content: str) -> Path:
    path.write_text(content)
    return path


# ---------------------------------------------------------------------------
# Renderers — one per file type
# ---------------------------------------------------------------------------

def _render_readme(spec: AgentSpec) -> str:
    in_scope = ", ".join(f"`{i.name}`" for i in spec.intents if i.in_scope)
    out_of_scope = ", ".join(f"`{i.name}`" for i in spec.intents if not i.in_scope) or "(none)"
    return dedent(f"""\
        # {spec.name}

        {spec.description}

        Domain: {spec.domain}
        Audience: {spec.audience}

        - **In-scope:** {in_scope}
        - **Out-of-scope:** {out_of_scope}
        - **Confidence threshold:** {spec.confidence_threshold}

        Generated by `scaffold_agent` from a spec. Mirrors the shape of the
        reference agent in `agent-skill-kit`.

        ## Run

        ```bash
        export ANTHROPIC_API_KEY=sk-ant-...
        python -m {spec.name}.runner --input "<example input>"
        ```

        ## To make this real

        Generated tools have stub `call()` functions that return `{{}}`. Fill
        them in with your actual backend integrations.

        ## Layout

        ```
        {spec.name}/
        ├── agent.yaml          # Manifest. Audit skills read this.
        ├── runner.py           # Agent loop.
        ├── prompts/            # system, classification, flow prompts, handoff.
        ├── tools/              # One module per tool. Fill in call() stubs.
        └── evals/routing/      # Starter golden set.
        ```
        """)


def _render_manifest(spec: AgentSpec) -> str:
    in_scope_names = [i.name for i in spec.intents if i.in_scope]
    out_of_scope_names = [i.name for i in spec.intents if not i.in_scope]

    lines = [
        f"# Manifest for the {spec.name} agent.",
        "# Audit skills read this for version/intent info.",
        "",
        f"agent: {spec.name}",
        f"version: 1",
        f"description: >",
        f"  {spec.description}",
        f"",
        f"model: claude-sonnet-4-5",
        f"",
        f"intents:",
        f"  in_scope:",
    ]
    for n in in_scope_names:
        lines.append(f"    - {n}")
    if out_of_scope_names:
        lines.append("  out_of_scope:")
        for n in out_of_scope_names:
            lines.append(f"    - {n}")
    else:
        lines.append("  out_of_scope: []")
    lines += [
        f"  fallback: unknown",
        f"",
        f"routing:",
        f"  confidence_threshold: {spec.confidence_threshold}",
        f"",
        f"prompts:",
        f"  system: 1",
        f"  classification: 1",
        f"  handoff: 1",
    ]
    for flow in spec.flows:
        lines.append(f"  {flow.intent}_flow: 1")
    lines += ["", "tools:"]
    for tool in spec.tools:
        lines += [
            f"  - name: {tool.name}",
            f"    version: 1",
            f"    purpose: {tool.purpose}",
        ]
    lines += [
        "",
        "evals:",
        "  routing:",
        "    golden_set: evals/routing/golden.jsonl",
        "    pass_threshold: 0.85",
        "  quality:",
        "    status: not_measured",
        "  regression:",
        "    status: not_measured",
        "",
    ]
    return "\n".join(lines)


def _render_system_prompt(spec: AgentSpec) -> str:
    in_scope_names = [i.name for i in spec.intents if i.in_scope]
    out_of_scope_names = [i.name for i in spec.intents if not i.in_scope]

    out_of_scope_clause = (
        ", ".join(f"`{n}`" for n in out_of_scope_names) + " are routed via the handoff prompt with no in-line analysis."
        if out_of_scope_names
        else "(no out-of-scope intents are currently defined)"
    )
    flows_list = ", ".join(f"`{n}_flow`" for n in in_scope_names)

    return f"""{{# version: 1 #}}
{{# system.j2 — orchestrator for {spec.name} #}}

You are the {spec.name} agent. {spec.description}

Audience: {spec.audience}.

## Operating principles

1. **Classify before you act.** Every input is classified into exactly one intent before any other action. If your classification confidence is below {spec.confidence_threshold}, route to `unknown` and escalate.

2. **Out-of-scope intents are escalated, not handled.** {out_of_scope_clause}

3. **Make your reasoning visible.** When you call a tool, your reason for the call is part of your output. When you reach a final decision, your reasoning belongs in the structured output, not in hidden state.

4. **Surface tool failures explicitly.** If a tool call fails, do not pretend it succeeded. State what you attempted, what failed, and what you can still determine without it.

## Your loop

Step 1: Read the input.

Step 2: Classify. Use the classification prompt.

Step 3: Branch on classification.
  - If `intent` is out-of-scope: produce a structured handoff via the handoff prompt. Stop.
  - If `confidence` < {spec.confidence_threshold}: produce a low-confidence handoff. Stop.
  - If `intent` is in-scope: dispatch to the matching flow ({flows_list}).

Step 4: In the flow, you may call tools. Make your reason for each tool call clear in your message text.

Step 5: Produce the final structured output as defined by the flow.
"""


def _render_classification_prompt(spec: AgentSpec) -> str:
    intent_lines = []
    for intent in spec.intents:
        scope_marker = "in-scope" if intent.in_scope else "out-of-scope"
        signals_str = "; ".join(intent.signals) if intent.signals else "(no specific signals)"
        intent_lines.append(
            f"- `{intent.name}` ({scope_marker}) — {intent.description}\n"
            f"  Signals: {signals_str}"
        )
    intents_block = "\n\n".join(intent_lines)
    fallback_line = "- `unknown` — when signals are ambiguous or below confidence threshold."

    return f"""{{# version: 1 #}}
{{# classification.j2 — routing prompt for {spec.name} #}}

Classify the following input into exactly one intent. Return your decision via the `submit_classification` tool.

## Intents

{intents_block}

{fallback_line}

## Confidence calibration

- `≥ 0.9` — multiple unambiguous signals point to one intent.
- `0.7–0.9` — signals point to one intent, some ambiguity.
- `0.5–0.7` — mixed or unclear signals. **Output `unknown` at this range.**
- `< 0.5` — genuinely ambiguous.

The {spec.confidence_threshold} threshold is enforced downstream — be honest about your confidence rather than reaching for it.

## How you submit your answer

Call the `submit_classification` tool exactly once with `intent`, `confidence`, and `reasoning`.

## The input

{{{{ user_input }}}}
"""


def _render_flow_prompt(spec: AgentSpec, flow: FlowSpec) -> str:
    intent_obj = next((i for i in spec.intents if i.name == flow.intent), None)
    intent_desc = intent_obj.description if intent_obj else flow.intent

    steps_str = "\n".join(f"{i+1}. {step}" for i, step in enumerate(flow.steps))

    output_fields_lines = []
    for f in flow.output_fields:
        output_fields_lines.append(f'  "{f["name"]}": "<{f["description"]}>"')
    output_schema = "{\n" + ",\n".join(output_fields_lines) + "\n}"

    available_tools = ", ".join(f"`{t.name}`" for t in spec.tools) or "(no tools defined)"

    return f"""{{# version: 1 #}}
{{# {flow.intent}_flow.j2 — handles inputs classified as `{flow.intent}` #}}

The input has been classified as `{flow.intent}` (confidence ≥ {spec.confidence_threshold}). {intent_desc}

## Steps

{steps_str}

## Available tools

{available_tools}

## Tool failure modes to handle

- Tool returns an error: surface it explicitly. Do not pretend the call succeeded. Note what was attempted and continue with what you have.
- Tool returns empty result: this may be a valid outcome, not a failure. Read the tool's description for the empty-result convention.

## Output

Return JSON matching this shape:

```json
{output_schema}
```

## What this flow does not do

- Does not act outside the {flow.intent} scope. If the input drifts toward a different intent, re-classify; do not improvise.
- Does not invent data when tools return nothing. Surface the gap.

## The input

Input — classified as `{flow.intent}` (confidence {{{{ classification.confidence }}}}):

{{{{ user_input }}}}
"""


def _render_handoff_prompt(spec: AgentSpec) -> str:
    return f"""{{# version: 1 #}}
{{# handoff.j2 — structured escalation for {spec.name} #}}

You are producing a handoff to a human. The receiving human needs to act on this without re-reading the original input from scratch.

## What goes in a handoff

1. **Summary.** What was the user asking, in plain language, one line.
2. **Classification.** What intent did the agent classify this as, with confidence and reasoning.
3. **Actions taken.** Which tools were called (if any), what was found.
4. **Escalation reason.** Out-of-scope intent? Low confidence? Tool failure?
5. **Suggested next step.** A concrete action the human should take.

## Output

Return JSON matching this shape:

```json
{{% raw %}}
{{
  "summary": "<one-line plain language summary>",
  "classification": {{ "intent": "<intent>", "confidence": <float>, "reasoning": "<from classification step>" }},
  "actions_taken": ["<bullet per action>"],
  "escalation_reason": "<out_of_scope | low_confidence | tool_failure | policy>",
  "suggested_next_step": "<concrete action>"
}}
{{% endraw %}}
```

For out-of-scope handoffs, do NOT summarize the content of the user's input beyond a one-line plain summary. Out-of-scope content is routed, not analyzed.

## The input

Input — classified as `{{{{ classification.intent }}}}` (confidence {{{{ classification.confidence }}}}):

{{{{ user_input }}}}

Escalation reason: {{{{ escalation_reason }}}}

Classifier reasoning: {{{{ classification.reasoning }}}}
"""


def _render_tool(tool: ToolSpec) -> str:
    schema_props = []
    schema_required = []
    for inp in tool.inputs:
        schema_props.append(
            f'        "{inp["name"]}": {{\n'
            f'            "type": "{inp["type"]}",\n'
            f'            "description": (\n'
            f'                "{inp["description"]}"\n'
            f'            ),\n'
            f'        }}'
        )
        schema_required.append(f'"{inp["name"]}"')

    schema_props_str = ",\n".join(schema_props)
    schema_required_str = ", ".join(schema_required)

    call_args = ", ".join(
        f"{inp['name']}: {_python_type(inp['type'])}" for inp in tool.inputs
    )

    # Build the tool description string piece by piece. Avoiding dedent here
    # because nested f-string + dedent + raw newlines is a syntax minefield.
    desc_lines = [tool.purpose, "", "Use this tool when:"]
    for c in tool.when_to_use:
        desc_lines.append(f"- {c}")
    desc_lines.append("")
    desc_lines.append("Do NOT use this tool when:")
    for c in tool.when_not_to_use:
        desc_lines.append(f"- {c}")
    desc_lines.append("")
    desc_lines.append(f"Output: {tool.output_shape}")
    description_text = "\\n".join(desc_lines)
    # Note: \\n above produces the literal two-character sequence \n in the
    # generated Python source — which Python then interprets as a newline
    # when the module is loaded. This keeps the description as a single
    # Python string literal rather than a multi-line concatenation.

    parts = []
    parts.append(f'"""\n{tool.name} — {tool.purpose}\n"""\n\n')
    parts.append("from typing import Any\n\n\n")
    parts.append(
        "# The definition is what the model sees. Audit skills "
        "(notably tool-description-audit) read this without\n"
        "# executing the tool. The description is treated as a "
        "prompt — clarity matters as much as accuracy.\n\n"
    )
    parts.append("definition: dict[str, Any] = {\n")
    parts.append(f'    "name": "{tool.name}",\n')
    parts.append(f'    "description": (\n')
    parts.append(f'        "{description_text}"\n')
    parts.append(f'    ),\n')
    parts.append(f'    "input_schema": {{\n')
    parts.append(f'        "type": "object",\n')
    parts.append(f'        "properties": {{\n')
    parts.append(schema_props_str + "\n")
    parts.append(f'        }},\n')
    parts.append(f'        "required": [{schema_required_str}],\n')
    parts.append(f'    }},\n')
    parts.append("}\n\n\n")
    parts.append(f"def call({call_args}) -> Any:\n")
    parts.append(f'    """\n')
    parts.append(f"    STUB. Replace with your actual integration.\n\n")
    parts.append(f"    Expected output: {tool.output_shape}\n")
    parts.append(f'    """\n')
    parts.append(f"    # TODO: implement against your real backend\n")
    parts.append(f"    return {{}}\n")
    return "".join(parts)


def _python_type(json_type: str) -> str:
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }.get(json_type, "Any")


def _render_tools_init(spec: AgentSpec) -> str:
    imports = ", ".join(t.name for t in spec.tools)
    if not imports:
        return '"""Tools package — no tools defined."""\n'
    return f'"""Tools for {spec.name}."""\nfrom . import {imports}\n\n__all__ = [{", ".join(repr(t.name) for t in spec.tools)}]\n'


def _render_runner(spec: AgentSpec) -> str:
    flow_map_entries = ",\n        ".join(
        f'"{f.intent}": "{f.intent}_flow"' for f in spec.flows
    )

    return dedent(f'''\
        """
        {spec.name} runner.

        Generated by scaffold_agent. Mirrors the shape of the reference agent's
        runner. Implements: classify-then-dispatch, tool-use loop, structured
        output, graceful out-of-scope and low-confidence handoffs.

        Run:
            python -m {spec.name}.runner --input "<example input>"
        """

        import argparse
        import json
        import os
        import sys
        from pathlib import Path
        from typing import Any

        import yaml
        from anthropic import Anthropic
        from jinja2 import Environment, FileSystemLoader, StrictUndefined

        from {spec.name}.tools import *  # noqa: F401,F403  — registered below


        REPO_ROOT = Path(__file__).parent
        PROMPT_DIR = REPO_ROOT / "prompts"
        MANIFEST_PATH = REPO_ROOT / "agent.yaml"


        def load_manifest() -> dict[str, Any]:
            with MANIFEST_PATH.open() as f:
                return yaml.safe_load(f)


        def load_prompts() -> Environment:
            return Environment(
                loader=FileSystemLoader(PROMPT_DIR),
                undefined=StrictUndefined,
                keep_trailing_newline=True,
            )


        def build_tool_registry() -> tuple[list[dict[str, Any]], dict[str, Any]]:
            from {spec.name} import tools as tools_pkg
            tool_modules = [getattr(tools_pkg, name) for name in tools_pkg.__all__]
            definitions = [t.definition for t in tool_modules]
            call_map = {{t.definition["name"]: t.call for t in tool_modules}}
            return definitions, call_map


        def classify(client: Anthropic, env: Environment, user_input: str, model: str, trace: list[str]) -> dict[str, Any]:
            classification_tool = {{
                "name": "submit_classification",
                "description": "Submit your classification. Call exactly once.",
                "input_schema": {{
                    "type": "object",
                    "properties": {{
                        "intent": {{"type": "string"}},
                        "confidence": {{"type": "number", "minimum": 0.0, "maximum": 1.0}},
                        "reasoning": {{"type": "string"}},
                    }},
                    "required": ["intent", "confidence", "reasoning"],
                }},
            }}

            template = env.get_template("classification.j2")
            prompt = template.render(user_input=user_input)
            trace.append("[classify] sending classification prompt")

            response = client.messages.create(
                model=model,
                max_tokens=1024,
                tools=[classification_tool],
                tool_choice={{"type": "tool", "name": "submit_classification"}},
                messages=[{{"role": "user", "content": prompt}}],
            )

            for block in response.content:
                if block.type == "tool_use" and block.name == "submit_classification":
                    result = dict(block.input)
                    trace.append(
                        f"[classify] intent={{result['intent']}} confidence={{result['confidence']:.2f}}"
                    )
                    return result

            trace.append("[classify] no tool call from model; escalating")
            return {{"intent": "unknown", "confidence": 0.0, "reasoning": "no classification submitted"}}


        def run_flow(client: Anthropic, env: Environment, flow_name: str, user_input: str,
                     classification: dict[str, Any], tool_definitions: list[dict[str, Any]],
                     tool_call_map: dict[str, Any], model: str, trace: list[str]) -> str:
            template = env.get_template(f"{{flow_name}}.j2")
            prompt = template.render(user_input=user_input, classification=classification)

            system_template = env.get_template("system.j2")
            system_prompt = system_template.render()

            messages: list[dict[str, Any]] = [{{"role": "user", "content": prompt}}]
            trace.append(f"[flow] entered {{flow_name}}")

            for _ in range(8):
                response = client.messages.create(
                    model=model,
                    max_tokens=2048,
                    system=system_prompt,
                    tools=tool_definitions,
                    messages=messages,
                )
                messages.append({{"role": "assistant", "content": response.content}})

                if response.stop_reason == "end_turn":
                    for block in response.content:
                        if block.type == "text":
                            return block.text
                    return ""

                if response.stop_reason != "tool_use":
                    return f"(stopped: {{response.stop_reason}})"

                tool_results = []
                for block in response.content:
                    if block.type != "tool_use":
                        continue
                    trace.append(f"[tool] {{block.name}}({{json.dumps(block.input)[:120]}})")
                    try:
                        result = tool_call_map[block.name](**block.input)
                    except Exception as e:
                        result = {{"error": "tool_exception", "detail": str(e)}}
                    tool_results.append({{
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps(result, default=str),
                    }})
                messages.append({{"role": "user", "content": tool_results}})

            return "(max iterations)"


        def handle(user_input: str) -> dict[str, Any]:
            manifest = load_manifest()
            env = load_prompts()
            client = Anthropic()
            model = manifest["model"]
            threshold = manifest["routing"]["confidence_threshold"]

            trace: list[str] = []
            classification = classify(client, env, user_input, model, trace)

            out_of_scope = manifest["intents"].get("out_of_scope") or []

            if classification["intent"] in out_of_scope:
                trace.append(f"[route] out-of-scope: {{classification['intent']}}")
                return _produce_handoff(client, env, user_input, classification, model, trace, "out_of_scope")

            if classification["confidence"] < threshold:
                trace.append(f"[route] low confidence; escalating")
                classification["intent"] = "unknown"
                return _produce_handoff(client, env, user_input, classification, model, trace, "low_confidence")

            flow_map = {{
                {flow_map_entries}
            }}
            flow_name = flow_map.get(classification["intent"])
            if flow_name is None:
                trace.append(f"[route] no flow for intent {{classification['intent']}}; escalating")
                return _produce_handoff(client, env, user_input, classification, model, trace, "policy")

            tool_definitions, tool_call_map = build_tool_registry()
            response = run_flow(
                client, env, flow_name, user_input, classification,
                tool_definitions, tool_call_map, model, trace,
            )
            return {{
                "decision": "handled_by_flow",
                "flow": flow_name,
                "classification": classification,
                "response": response,
                "trace": trace,
            }}


        def _produce_handoff(client, env, user_input, classification, model, trace, reason):
            template = env.get_template("handoff.j2")
            prompt = template.render(
                user_input=user_input,
                classification=classification,
                escalation_reason=reason,
            )
            response = client.messages.create(
                model=model,
                max_tokens=1024,
                messages=[{{"role": "user", "content": prompt}}],
            )
            text = response.content[0].text if response.content else ""
            trace.append(f"[handoff] produced for {{reason}}")
            return {{
                "decision": "handoff",
                "escalation_reason": reason,
                "classification": classification,
                "handoff": text,
                "trace": trace,
            }}


        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument("--input", required=True, help="Input text for the agent")
            parser.add_argument("--show-trace", action="store_true")
            args = parser.parse_args()

            if not os.environ.get("ANTHROPIC_API_KEY"):
                print("ANTHROPIC_API_KEY not set", file=sys.stderr)
                sys.exit(1)

            result = handle(args.input)
            print(json.dumps({{k: v for k, v in result.items() if k != "trace"}}, indent=2, default=str))
            if args.show_trace:
                print("\\n--- trace ---", file=sys.stderr)
                for line in result.get("trace", []):
                    print(line, file=sys.stderr)


        if __name__ == "__main__":
            main()
        ''')


def _render_golden_set(spec: AgentSpec) -> str:
    lines = []
    for ex in spec.eval_examples:
        lines.append(json.dumps({
            "description": ex.get("description", ""),
            "expected_intent": ex.get("expected_intent", "unknown"),
            "expected_min_confidence": 0.7,
            "notes": ex.get("notes", ""),
        }))
    return "\n".join(lines) + ("\n" if lines else "")
